FoundationEnglishScore = float(input("Put your Foundation English Score here :"))
GeneralBusinessScore = float(input("Put your General Business Score here :"))
IntroductiontoComputerSystemsScore = float(input("Put your Introduction to Computer System Here :"))
ComputerProgrammingScore = float(input("Put your Computer Programming Score here :"))
print( "Foundation English :",FoundationEnglishScore)
print ("General Business :", GeneralBusinessScore)
print("Introductionto Computer System :",IntroductiontoComputerSystemsScore)
print ("Computer Programming :",ComputerProgrammingScore)