a = int(input("first num :"))
b = int(input("Second num :"))
plus = a+b
minus = a-b
time = a*b
divide = a/b
print(a,"+",b,"=",plus)
print(a,"-",b,"=",minus)
print(a,"*",b,"=",time)
print(a,"/",b,"=",divide)